language: java
jdk:
 - openjdk11
env:
 global:
  - GITHUB_ACTOR=araqnid
  - secure: "v9sSjhRwhVFlqtrkwwqL+s27LlUy8ohleykNxXpnbhG8MtbzdcSSvlGftjaLUPfsUXj6RHIjVUO5IxLT+Hu+BV3B1BSFLf2wIFqwYKpcn9C9Cr0S23Zb/rX+yOv8B+ZZgUrKXgJUx1S1NLxa7px3lZd00PXl7Av1R89rzGC1EATcBLCg8LiprQrhWvxEIk3IL9bkKlrX1zKohBD7PCwAPc24TUtUiAZqst+2zLzMkdXVlI7krGpqpEZXtUwIfZVJou+McPWj55gJIIGfb2C6oETYPBy/pjPkLpqA+99XOkx8H8mhzfueQkWz9IgGkzu7bgbGLUC+kqMtJvmZ2Mg3lrgffqzMm0CQ/TY4QW8FinEyL4BfFQE/0KWG6hSeoDamOLW/pRwA+7lyjNw31XhkYoSYcHNGpZYAoO1IynB95r1Q1dTZEF4RR+G8Xis3a2u6XAG106HZuGywH1m6ewaK34lMIAUQr5GtwK5Pd8Fw718z0cAT5nOa4A+HPCQXkL41UcXBsFqrTMB6wc66a6MkeZ57ic8J84L0yPfSefTYKRMJLUmFxFJbvvSOIV5xtacocBbogAzvn2DHU88CYuxOBqNh4Zb017LyIE2tghwY+2xunhFsbiEtyBO3EJ3AHDVYpi0ASaCWQSkeom9sJwvHJaEn8vS6AdjlYQc3fBE5aSo="
